# -*- coding: utf-8 -*-
"""Data_cleaning_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rI6cjtHOgawSk_PktwrU9fmqnBwaUNwy
"""

#Importing Libraries

import pandas as pd
import numpy as np

# Load Dataset

df=pd.read_csv('/content/drive/MyDrive/hr_data_200_rows.csv')

df.head()

# Checking for null value.

df.isnull().sum()

df.duplicated().sum()

df.shape

print(df.dtypes)

"""#Datatype Conversion

"""

# Convert data types into numeric.

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Experience'] = pd.to_numeric(df['Experience'], errors='coerce')

print(df.dtypes)

"""#Handling Missing Values"""

# Numeric : Fill with median/mean

df['Age'].fillna(df['Age'].median(),inplace = True)
df['Salary'].fillna(df['Salary'].mean(),inplace = True)
df['Experience'].fillna(df['Experience'].mean(),inplace = True)

#Categorical : Fill with mode

df['Gender'].fillna(df['Gender'].mode()[0],inplace = True)
df['Education'].fillna(df['Education'].mode()[0],inplace = True)

# Showing data after filling the missing values.
df.head()

# Again check for null value

df.isnull().sum()

"""# Encode Categorical Columns

"""

# Encode Categorical Columns

df_encoded = pd.get_dummies(df, columns=['Department', 'Attrition','Education','Gender'], drop_first=True)

# print encoded value.

display(df_encoded.head())

"""#Standardize numerical columns."""

from sklearn.preprocessing import LabelEncoder, StandardScaler
col_to_scale = ['Age', 'Salary','Experience']

#Standardization for ml using in ml model .

scaler = StandardScaler()
df_encoded[col_to_scale] = scaler.fit_transform(df_encoded[col_to_scale])

# Save cleaned data
df.to_csv('hr_data_cleaned.csv', index=False)

print("✅ Data cleaning complete. Saved as hr_data_cleaned.csv.")